name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

  schedule:
    - cron: "50 0 * * *"  # daily at 00:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: joseph-data/yearly_explorer
          hf_token: ${{ secrets.HF_TOKEN }}